[build]
  publish = "client/build"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect specific routes to index.html (React Router)
[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/add-expense"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/expenses"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reports"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/categories"
  to = "/index.html"
  status = 200
