[build]
  publish = "client/build"
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
